# Generated by Django 5.2.1 on 2025-05-23 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_local', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('ip_nodo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_nodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='historialenvio',
            name='ip_nodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_local.nodo'),
        ),
    ]
