# Generated by Django 5.2.1 on 2025-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_local', '0002_nodo_historialenvio_ip_nodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlenvio',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlenvio',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleruta',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleruta',
            name='motivo_fallo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
