# Generated by Django 5.2.1 on 2025-05-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_local', '0003_controlenvio_fecha_envio_controlenvio_recibido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialenvio',
            name='detalle_ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_local.detalleruta'),
        ),
    ]
