# Generated by Django 5.2.1 on 2025-05-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_local', '0004_historialenvio_detalle_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialenvio',
            name='detalle_ruta',
        ),
    ]
